sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    bucket-name: sky-take-out-wjh
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-secret: jhQdfCTY4PCKOqqIZPLtXXi3SuPeyx
    access-key-id: LTAI5t8siAfE1243hEjZjEaC
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wxc633bea88cee3808
    secret: 6862473c3c8535fe20a261af8d285c2e
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php